apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: 2c4cb3bac8aea7bdb6a4e32e4f
        volumeMounts:
          - name: postgres
            mountPath: /var/lib/postgresql
      volumes:
        - name: postgres
          nfs:
            server: nfs-server.default.svc.cluster.local
            path: /postgresql
